export enum QueryKeys {
  INDUSTRY = "industry",
  COUNTRIES = "countries",
  CURRENCIES = "currencies",
  CURRENCY = "CURRENCY",
  TIMEZONE = "timezone",
  PLANS = "plans",
  BRANDS = "brands",
  BRAND = "brand",
  CATEGORIES = "categories",
  CATEGORY = "category",
  SUB_CATEGORIES = "sub_categories",
  SUB_CATEGORY = "sub_category",
  UNITS = "units",
  UNIT = "unit",
  SUB_UNITs = "sub_units",
  SUB_UNIT = "sub_unit",
  ME = "me",
  WARRANTIES = "warranties",
  WARRANTY = "warranty",
}
