import { QrCodeIcon, ShieldCheckIcon } from "lucide-react";


export default function SecuritySettings() {
  return (
    <div className="p-6 bg-white rounded-lg shadow-sm dark:bg-gray-850">
      <div className="flex items-start gap-4">
        <ShieldCheckIcon className="w-8 h-8 text-brand-500 mt-1" />
        
        <div className="flex-1">
          <h3 className="text-lg font-semibold text-gray-800 dark:text-gray-100">
            Multi-Factor Authentication (MFA)
          </h3>
          
          <div className="mt-4 space-y-4">
            {/* Authenticator App Section */}
            <div className="p-4 border rounded-lg dark:border-gray-700">
              <div className="flex items-center justify-between">
                <div>
                  <h4 className="font-medium text-gray-800 dark:text-gray-200">
                    Authenticator App
                  </h4>
                  <p className="text-sm text-gray-600 dark:text-gray-400 mt-1">
                    Use time-based OTPs generated by authenticator apps
                  </p>
                </div>
                
                <button 
                  className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-brand-500 rounded-lg hover:bg-brand-600"
                //   onClick={() => setIsSetupModalOpen(true)}
                >
                  <QrCodeIcon className="w-5 h-5" />
                  Set Up Now
                </button>
              </div>

              <div className="mt-4 text-sm">
                <p className="text-gray-600 dark:text-gray-400">
                  Recommended apps:
                </p>
                <div className="flex gap-4 mt-2">
                  <a href="#" className="flex items-center gap-2 text-brand-500">
                    <img src="../../../src/icons/google-authenticator.svg"  className="w-6 h-6 opacity-80 dark:invert" />
                    Google Authenticator
                  </a>
                  <a href="#" className="flex items-center gap-2 text-brand-500">
                    <img src="../../../src/icons/microsoft-authenticator.svg" className="w-6 h-6" />
                    Microsoft Authenticator
                  </a>
                </div>
              </div>
            </div>

            {/* Backup Methods Section */}
            <div className="p-4 border rounded-lg dark:border-gray-700">
              <h4 className="font-medium text-gray-800 dark:text-gray-200">
                Backup Methods
              </h4>
              <p className="text-sm text-gray-600 dark:text-gray-400 mt-2">
                Generate recovery codes for emergency access
              </p>
              <button className="mt-3 text-sm text-brand-500 hover:underline">
                Manage Recovery Codes
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}